### PR TITLE
Optimize twin prime algorithm

### PR DESCRIPTION
**Pull request by scribblemaniac**
The "skip 4 numbers" optimization you had will cause certain twin primes to be missed. For example, 3 and 5 are both prime so result !== null. You then add 4 to number, and then another 2 at the end of the loop, so the number is now 3+4+2=9 and you've completely skipped over the pair 5, 7. This happens with an prime triplet or where the prime gap is 4.

After fixing that, I couldn't help but add a few other easy optimizations. The project should run ~4x faster with this code.

### CODE REVIEW

**Comment by scribblemaniac** [comment]
@sau412 Are you going to take a look at my PRs? I'd love to see a new project get added, and this one is even more important. Anyone using it right now is quite frankly wasting their time when your code is <strike>not producing correct results and is</strike> far slower.

**Comment by sau412** [comment]
@scribblemaniac something wrong with github notifications, sorry for delay

**Comment by sau412** [comment]
There are no prime quartets exists.
If you have numbers n, n+1, n+2, n+3, n+4, n+5, n+6 and (n, n+2) is prime twins, then n+4 is not prime, because one of numbers (n, n+2, n+3+1) should divide by three without remainder. Next potential prime is n+6.

**Comment by scribblemaniac** [comment]
Ah yes sorry you're right, my mistake 😞 . Well my improvements still stand, and I have re-added your optimization.

**Comment by sau412** [comment]
Need some time to check last optimization

**Comment by scribblemaniac** [comment]
Upon learning more about twin primes, I am able to simplify the code and optimize even further. In testing, these latest changes are ~6.5x faster than the version you are currently using. It should be easier to review now too.

P.S. If you leave this to sit forever, chances are I or someone else will just end up modding their client to use this code and rake in your 💰

**Comment by sau412** [comment]
I merged changes, but not applied yet. I going to apply tomorrow

**Comment by sau412** [comment]
Done, now your version is active!

**Pull request merged**
