### PR TITLE
Add new project: Consecutive Power Primes

### PR DESCRIPTION
**Pull request by scribblemaniac**
This PR fixes some issues and implements a completely new project that searches for perfect nth-roots that can be expressed as the sum of consecutive primes to the power of n. Inspired by [Puzzle 392](https://www.primepuzzles.net/puzzles/puzz_393.htm) and [Puzzle 443](https://www.primepuzzles.net/puzzles/puzz_443.htm) from primepuzzles.net. As far as I am aware there is currently no proof for or against the existence of such a number for n > 2, so any matching numbers discovered by this project would be of interest.

Recommended settings for this project are as follows:
- start_number = 15000000. Anything >= 238 will definitely work with the current code, it is just important that you have at least MAX_PRIME_SEQUENCE_SIZE primes >=3 and <= start_number. I've already ran through the first 15 million numbers locally which is why I recommend skipping them.
- end_number = 9007199254740991. You may recognize this as Number.MAX_SAFE_INTEGER. The project can handle numbers larger than this thanks to the BigInteger.js library, however the code running the workers and generating the workunits would have to be modified as well. This number won't be reached any time soon anyway.
- step = 25000. In my personal testing, this results in approximately the same amount of time per workunit as the current (unoptimized) twin-primes project. The time required will go up (or possibly even down, I'm not sure) as the numbers get larger, so this or the price may need to be adjusted in the future.
- retries >= 2. The results include a unique validation_hash so that they cannot be guessed without doing most of the work.

*Important note:* I was unsure of how to fill project.function. As far as I can tell, you've just put the entire script file in it, but that's kind of redundant and difficult to manage, so I replaced it with a file path to the worker script. This will break the current project until you update it to "twin_primes.js".

### CODE REVIEW

**Comment by sau412** [comment]
Project.function is selected because I think to implement online function editor.

**Comment by scribblemaniac** [comment]
Thanks!

**Comment by sau412** [comment]
@scribblemaniac I decided to leave only one project on microgrid. So I disabled Consecutive Power Primes yesterday.
Latest completed workunit is numbers between 1548611343 and 1548636343. Full results available here: https://arikado.ru/consecutive_power_primes.csv.bz2

**Comment by scribblemaniac** [comment]
That's unfortunate to hear. Thank you for hosting and support the project to this point. Even though no example solutions were found for the problem this project was investigating, the work done provides useful information nevertheless as is suggests that there may be a non-trivial lower-bound for the sequence size, or that solutions do not exist for powers higher than 2.

I actually started reworking this project last month as there was still lots of room for optimization, documentation, and the I believe the parameters need to be tweaked given the lack of success with finding any examples so far (primarily increasing the MAX_PRIME_SEQUENCE_SIZE which unfortunately is not reasonable to do with the current implementation). Work on this has to be stopped due to personal circumstance, but I will probably pick it up at some point.

Was there something in particular wrong with this project that resulted in it being removed or do you just want this project to be solely about finding twin primes? If it is the latter option, perhaps you should consider rebranding this project to reflect that, and at the very least update the readme to indicate that you are not interested in additional projects now.

**Comment by sau412** [comment]
> Was there something in particular wrong with this project that resulted in it being removed or do you just want this project to be solely about finding twin primes? If it is the latter option, perhaps you should consider rebranding this project to reflect that, and at the very least update the readme to indicate that you are not interested in additional projects now.

Nothing totally wrong with your project. Two reasons of deletion exists.

First, I have some server issues, it shows 502/504 errors with no visible reason. Still investigate it. I thought it was DB overload, but it is not.

Second is microgrid has no well-thought-out project management and balancing mechanism. Very few users choose another project, and I have heaps of half-done workunits. They are done only by one user, and I cannot remove them, and I cannot reward user properly (because workunits are incomplete).

I not decided yet, will I add project management here, or leave only one project. May be I will fork microgrid into several sub-projects. Need some time to think.

**Comment by scribblemaniac** [comment]
I see. For what it's worth, I think the concept of having a collection of projects is a good idea. I agree that this isn't structured well currently to balance the projects, since the value of a workunit is hard-coded for each project. I haven't tested it recently but in all likelihood the latest workunits for this project were much more difficult than the first workunits for example. The only solution I have would be to take a approach similar to what gridcoin does to balance out the varying credit rewards of all the whitelisted projects: rewarding each project equally, and then rewarding individual users based on their the proportion of work they did for each project. That would incentivize a more balanced efforts between projects and would eliminate the need to set a fixed reward for the workunits of each project.

A simple example of what I mean. Say in the span of a day the following work is done:
User 1: 20 workunits on Project 1
User 2: 5 workunits on Project 2
User 3: 5 workunits on Project 1 and 5 workunits on Project 2
Then say you set a reward of 10 GRC/day. Then Project 1 and Project 2 are both allocated a 5 GRC reward for the day's work. Individual rewards would be the sum of `<total_project_reward>*<wu_completed_by_user_for_project>/<total_wu_completed_for_project>` for each project. User 1 gets 4 GRC (5\*20/25). User 2 gets 2.5 GRC (5\*5/10). User 3 gets 3.5 GRC ((5\*5/25)+(5\*5/10)). If you think some workunits should be worth more than another within a project, then you would have to follow the way BOINC/Gridcoin works even more closely and make a credit system. If you don't want to reward projects equally, you could set each project to have a fixed proportion of the total rewards. Lots of little ways you could tweak it, but that's the general idea.

**Pull request merged**
